version: 2.1

executors:
  medium-node-executor:
    docker:
      - image: cimg/node:lts
    resource_class: medium

commands:
  install-node-modules:
    steps:
      - restore_cache:
          keys:
            - v1-node_modules-{{ checksum "package-lock.json" }}
      - run: |
          if [ ! -d node_modules ]; then
            npm ci
          fi
      - save_cache:
          key: v1-node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  playwright-install:
    steps:
      - run:
          name: Install Playwright browsers
          command: npx playwright install --with-deps

jobs:
  circleci-pw-tests:
    executor: medium-node-executor
    parallelism: 2
    steps:
      - checkout
      - install-node-modules
      - playwright-install
      - run:
          name: Run Playwright tests based on CircleCI timings
          command: |
            PLAYWRIGHT_JUNIT_OUTPUT_NAME=tests/playwright/results.xml
            TESTFILES=$(circleci tests glob "tests/**/*.spec.ts")
            circleci tests run --command="xargs npx playwright test --config=playwright.config.ts" --verbose --split-by=timings --time-default=1s
      - store_artifacts:
          path: tests/playwright/report
          name: Store HTML test reports
      - store_test_results:
          name: Store XML test reports
          path: tests/playwright/results.xml
  default-pw-tests:
    executor: medium-node-executor
    parallelism: 2
    steps:
      - checkout
      - install-node-modules
      - playwright-install
      - run:
          name: Run Playwright tests based on PW timings
          command: |
            SHARD_INDEX=$((${CIRCLE_NODE_INDEX} + 1))
            npx playwright test --shard=${SHARD_INDEX}/${CIRCLE_NODE_TOTAL}
      - store_artifacts:
          path: tests/playwright/report
          name: Store HTML test reports
      - store_test_results:
          name: Store XML test reports
          path: tests/playwright/results.xml

workflows:
  run-tests:
    jobs:
      - circleci-pw-tests
      - default-pw-tests
