version: 2.1

commands:
  install-node-modules:
    steps:
      - restore_cache:
          keys:
            - v1-node_modules-{{ checksum "package-lock.json" }}
      - run: |
          if [ ! -d node_modules ]; then
            npm ci
          fi
      - save_cache:
          key: v1-node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  playwright-install:
    steps:
      - run:
          name: Install Playwright browsers
          command: npx playwright install --with-deps

jobs:
  e2e-tests:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - install-node-modules
      - playwright-install
      - run:
          name: Run Playwright tests
          command: npx playwright test
      - store_artifacts:
          path: tests/playwright/report
          name: Store HTML test reports
      - store_test_results:
          name: Store XML test reports
          path: tests/playwright/results

workflows:
  build-test:
    jobs:
      - e2e-tests
