version: 2.1

commands:
  install-node-modules:
    steps:
      - restore_cache:
          keys:
            - v1-node_modules-{{ checksum "package-lock.json" }}
      - run: |
          if [ ! -d node_modules ]; then
            npm ci
          fi
      - save_cache:
          key: v1-node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  playwright-install:
    steps:
      - run:
          name: Install Playwright browsers
          command: npx playwright install --with-deps

jobs:
  e2e-tests:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - install-node-modules
      - playwright-install
      - run:
          name: Run Playwright tests
          command: npx playwright test
      - store_artifacts:
          path: playwright-report/
          destination: playwright-report
      - store_test_results:
          path: test-results/

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - e2e-tests:
          context: org-global
